/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "CosNaming.h"

/*  Interface  */
CORBA_boolean CosNaming_NamingContext__is_a(CORBA_CosNaming_NamingContext _obj, const CORBA_char * id, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&id;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_bind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&obj;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[1], NULL, _args, ev );
}
void CosNaming_NamingContext_rebind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&obj;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[2], NULL, _args, ev );
}
void CosNaming_NamingContext_bind_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&nc;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[3], NULL, _args, ev );
}
void CosNaming_NamingContext_rebind_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&nc;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[4], NULL, _args, ev );
}
CORBA_Object CosNaming_NamingContext_resolve(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CORBA_Object _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[5], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_unbind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[6], NULL, _args, ev );
}
CosNaming_NamingContext CosNaming_NamingContext_new_context(CORBA_CosNaming_NamingContext _obj, CORBA_Environment *ev)
{
  CosNaming_NamingContext _ORBIT_retval;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[7], (void **)&_ORBIT_retval, NULL, ev );
  return _ORBIT_retval;
}
CosNaming_NamingContext CosNaming_NamingContext_bind_new_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CosNaming_NamingContext _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[8], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_destroy(CORBA_CosNaming_NamingContext _obj, CORBA_Environment *ev)
{
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[9], NULL, NULL, ev );
}
void CosNaming_NamingContext_list(CORBA_CosNaming_NamingContext _obj, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CosNaming_BindingIterator* bi, CORBA_Environment *ev)
{
  void * _args[3];
  _args[0] = (void *)&how_many;
  _args[1] = bl;
  _args[2] = &bi;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[10], NULL, _args, ev );
}
/*  End of Interface  */
/*  Interface  */
CORBA_boolean CosNaming_BindingIterator_next_one(CORBA_CosNaming_BindingIterator _obj, CosNaming_Binding** b, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[1];
  _args[0] = b;
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_boolean CosNaming_BindingIterator_next_n(CORBA_CosNaming_BindingIterator _obj, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&how_many;
  _args[1] = bl;
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[1], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_BindingIterator_destroy(CORBA_CosNaming_BindingIterator _obj, CORBA_Environment *ev)
{
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[2], NULL, NULL, ev );
}
/*  End of Interface  */
/*  Interface  */
CosNaming_NamingContextExt_StringName CosNaming_NamingContextExt_to_string(CORBA_CosNaming_NamingContextExt _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_StringName _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CosNaming_Name* CosNaming_NamingContextExt_to_name(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * sn, CORBA_Environment *ev)
{
  CosNaming_Name* _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&sn;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[1], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CosNaming_NamingContextExt_URLString CosNaming_NamingContextExt_to_url(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * addr, const CORBA_char * sn, CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_URLString _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&addr;
  _args[1] = (void *)&sn;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[2], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_Object CosNaming_NamingContextExt_resolve_str(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * n, CORBA_Environment *ev)
{
  CORBA_Object _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&n;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[3], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
/*  End of Interface  */
