/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "CosNaming.h"

/*  Interface  */
CORBA_boolean CosNaming_NamingContext__is_a(CORBA_CosNaming_NamingContext _obj, const CORBA_char * id, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&id;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_bind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&obj;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[1], NULL, _args, ev );
}
void CosNaming_NamingContext_rebind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&obj;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[2], NULL, _args, ev );
}
void CosNaming_NamingContext_bind_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&nc;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[3], NULL, _args, ev );
}
void CosNaming_NamingContext_rebind_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev)
{
  void * _args[2];
  _args[0] = (void *)n;
  _args[1] = (void *)&nc;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[4], NULL, _args, ev );
}
CORBA_Object CosNaming_NamingContext_resolve(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CORBA_Object _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[5], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_unbind(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[6], NULL, _args, ev );
}
CosNaming_NamingContext CosNaming_NamingContext_new_context(CORBA_CosNaming_NamingContext _obj, CORBA_Environment *ev)
{
  CosNaming_NamingContext _ORBIT_retval;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[7], (void **)&_ORBIT_retval, NULL, ev );
  return _ORBIT_retval;
}
CosNaming_NamingContext CosNaming_NamingContext_bind_new_context(CORBA_CosNaming_NamingContext _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CosNaming_NamingContext _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[8], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_NamingContext_destroy(CORBA_CosNaming_NamingContext _obj, CORBA_Environment *ev)
{
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[9], NULL, NULL, ev );
}
void CosNaming_NamingContext_list(CORBA_CosNaming_NamingContext _obj, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CosNaming_BindingIterator* bi, CORBA_Environment *ev)
{
  void * _args[3];
  _args[0] = (void *)&how_many;
  _args[1] = bl;
  _args[2] = &bi;
  invokeMethod (_obj, &CosNaming_NamingContext__imp.methods[10], NULL, _args, ev );
}
/*  End of Interface  */
/*  Interface  */
CORBA_boolean CosNaming_BindingIterator_next_one(CORBA_CosNaming_BindingIterator _obj, CosNaming_Binding** b, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[1];
  _args[0] = b;
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_boolean CosNaming_BindingIterator_next_n(CORBA_CosNaming_BindingIterator _obj, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CORBA_Environment *ev)
{
  CORBA_boolean _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&how_many;
  _args[1] = bl;
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[1], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void CosNaming_BindingIterator_destroy(CORBA_CosNaming_BindingIterator _obj, CORBA_Environment *ev)
{
  invokeMethod (_obj, &CosNaming_BindingIterator__imp.methods[2], NULL, NULL, ev );
}
/*  End of Interface  */
/*  Interface  */
CosNaming_NamingContextExt_StringName CosNaming_NamingContextExt_to_string(CORBA_CosNaming_NamingContextExt _obj, CosNaming_Name* n, CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_StringName _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)n;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CosNaming_Name* CosNaming_NamingContextExt_to_name(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * sn, CORBA_Environment *ev)
{
  CosNaming_Name* _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&sn;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[1], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CosNaming_NamingContextExt_URLString CosNaming_NamingContextExt_to_url(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * addr, const CORBA_char * sn, CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_URLString _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&addr;
  _args[1] = (void *)&sn;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[2], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_Object CosNaming_NamingContextExt_resolve_str(CORBA_CosNaming_NamingContextExt _obj, const CORBA_char * n, CORBA_Environment *ev)
{
  CORBA_Object _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&n;
  invokeMethod (_obj, &CosNaming_NamingContextExt__imp.methods[3], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
/*  End of Interface  */


#if __cplusplus
CosNaming::NamingContext_ptr
CosNaming::NamingContext::_narrow(CORBA::Object_ptr obj)
{
  return CORBA_Narrow<CosNaming::NamingContext>::narrow(obj);
}

CORBA::Boolean
 CosNaming::NamingContext::_is_a(const CORBA_char * id)
{
  CORBA_boolean tmp =  CosNaming_NamingContext__is_a(this->_impl,CORBA_string_CppInArg(id), &this->ev);
  return CORBA::Boolean_helper::_retnew(tmp);
}

void
 CosNaming::NamingContext::bind(const Name& n, CORBA::Object_ptr obj)
{
 CosNaming_NamingContext_bind(this->_impl,CosNaming::Name_CppInArg(n), CORBA::Object_CppInArg(obj), &this->ev);
  return;
 }

void
 CosNaming::NamingContext::rebind(const Name& n, CORBA::Object_ptr obj)
{
 CosNaming_NamingContext_rebind(this->_impl,CosNaming::Name_CppInArg(n), CORBA::Object_CppInArg(obj), &this->ev);
  return;
 }

void
 CosNaming::NamingContext::bind_context(const Name& n, NamingContext_ptr nc)
{
 CosNaming_NamingContext_bind_context(this->_impl,CosNaming::Name_CppInArg(n), CosNaming::NamingContext_CppInArg(nc), &this->ev);
  return;
 }

void
 CosNaming::NamingContext::rebind_context(const Name& n, NamingContext_ptr nc)
{
 CosNaming_NamingContext_rebind_context(this->_impl,CosNaming::Name_CppInArg(n), CosNaming::NamingContext_CppInArg(nc), &this->ev);
  return;
 }

CORBA::Object_ptr
 CosNaming::NamingContext::resolve(const Name& n)
{
  CORBA_Object tmp =  CosNaming_NamingContext_resolve(this->_impl,CosNaming::Name_CppInArg(n), &this->ev);
  return CORBA::Object_helper::_retnew(tmp);
}

void
 CosNaming::NamingContext::unbind(const Name& n)
{
 CosNaming_NamingContext_unbind(this->_impl,CosNaming::Name_CppInArg(n), &this->ev);
  return;
 }

CosNaming::NamingContext_ptr
 CosNaming::NamingContext::new_context()
{
  CosNaming_NamingContext tmp =  CosNaming_NamingContext_new_context(this->_impl,&this->ev);
  return CosNaming::NamingContext_helper::_retnew(tmp);
}

CosNaming::NamingContext_ptr
 CosNaming::NamingContext::bind_new_context(const Name& n)
{
  CosNaming_NamingContext tmp =  CosNaming_NamingContext_bind_new_context(this->_impl,CosNaming::Name_CppInArg(n), &this->ev);
  return CosNaming::NamingContext_helper::_retnew(tmp);
}

void
 CosNaming::NamingContext::destroy()
{
 CosNaming_NamingContext_destroy(this->_impl,&this->ev);
  return;
 }

void
 CosNaming::NamingContext::list(CORBA::ULong how_many, BindingList_out bl, BindingIterator_ptr bi)
{
 CosNaming_NamingContext_list(this->_impl,CORBA::ULong_CppInArg(how_many), CosNaming::BindingList_CppOutArg(bl), CosNaming::BindingIterator_CppOutArg(bi), &this->ev);
  return;
 }
CosNaming::BindingIterator_ptr
CosNaming::BindingIterator::_narrow(CORBA::Object_ptr obj)
{
  return CORBA_Narrow<CosNaming::BindingIterator>::narrow(obj);
}

CORBA::Boolean
 CosNaming::BindingIterator::next_one(Binding_out b)
{
  CORBA_boolean tmp =  CosNaming_BindingIterator_next_one(this->_impl,CosNaming::Binding_CppOutArg(b), &this->ev);
  return CORBA::Boolean_helper::_retnew(tmp);
}

CORBA::Boolean
 CosNaming::BindingIterator::next_n(CORBA::ULong how_many, BindingList_out bl)
{
  CORBA_boolean tmp =  CosNaming_BindingIterator_next_n(this->_impl,CORBA::ULong_CppInArg(how_many), CosNaming::BindingList_CppOutArg(bl), &this->ev);
  return CORBA::Boolean_helper::_retnew(tmp);
}

void
 CosNaming::BindingIterator::destroy()
{
 CosNaming_BindingIterator_destroy(this->_impl,&this->ev);
  return;
 }
CosNaming::NamingContextExt_ptr
CosNaming::NamingContextExt::_narrow(CORBA::Object_ptr obj)
{
  return CORBA_Narrow<CosNaming::NamingContextExt>::narrow(obj);
}

CosNaming::NamingContextExt::StringName
 CosNaming::NamingContextExt::to_string(const Name& n)
{
  CosNaming_NamingContextExt_StringName tmp =  CosNaming_NamingContextExt_to_string(this->_impl,CosNaming::Name_CppInArg(n), &this->ev);
  return CosNaming::NamingContextExt::StringName_helper::_retnew(tmp);
}

CosNaming::Name*
 CosNaming::NamingContextExt::to_name(const CORBA_char * sn)
{
  CosNaming_Name* tmp =  CosNaming_NamingContextExt_to_name(this->_impl,CosNaming::NamingContextExt::StringName_CppInArg(sn), &this->ev);
  return CosNaming::Name_helper::_retnew(tmp);
}

CosNaming::NamingContextExt::URLString
 CosNaming::NamingContextExt::to_url(const CORBA_char * addr, const CORBA_char * sn)
{
  CosNaming_NamingContextExt_URLString tmp =  CosNaming_NamingContextExt_to_url(this->_impl,CosNaming::NamingContextExt::Address_CppInArg(addr), CosNaming::NamingContextExt::StringName_CppInArg(sn), &this->ev);
  return CosNaming::NamingContextExt::URLString_helper::_retnew(tmp);
}

CORBA::Object_ptr
 CosNaming::NamingContextExt::resolve_str(const CORBA_char * n)
{
  CORBA_Object tmp =  CosNaming_NamingContextExt_resolve_str(this->_impl,CosNaming::NamingContextExt::StringName_CppInArg(n), &this->ev);
  return CORBA::Object_helper::_retnew(tmp);
}

#endif /* __cplusplus */
