/* This is a template file generated by command */
/* rtorb-idl --skeleton-impl CosNaming.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "CosNaming-skelimpl.h"

/*** epv structures ***/
static PortableServer_ServantBase__epv impl_CosNaming_NamingContext_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_CosNaming_NamingContext__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_CosNaming_NamingContext__epv impl_CosNaming_NamingContext_epv = {
    NULL, /* _private */
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_CosNaming_NamingContext__is_a,
    (void (*)(void *, CosNaming_Name*, CORBA_Object, CORBA_Environment *))&impl_CosNaming_NamingContext_bind,
    (void (*)(void *, CosNaming_Name*, CORBA_Object, CORBA_Environment *))&impl_CosNaming_NamingContext_rebind,
    (void (*)(void *, CosNaming_Name*, CosNaming_NamingContext, CORBA_Environment *))&impl_CosNaming_NamingContext_bind_context,
    (void (*)(void *, CosNaming_Name*, CosNaming_NamingContext, CORBA_Environment *))&impl_CosNaming_NamingContext_rebind_context,
    (CORBA_Object (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_resolve,
    (void (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_unbind,
    (CosNaming_NamingContext (*)(void *, CORBA_Environment *))&impl_CosNaming_NamingContext_new_context,
    (CosNaming_NamingContext (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_bind_new_context,
    (void (*)(void *, CORBA_Environment *))&impl_CosNaming_NamingContext_destroy,
    (void (*)(void *, CORBA_unsigned_long, CosNaming_BindingList**, CosNaming_BindingIterator*, CORBA_Environment *))&impl_CosNaming_NamingContext_list,
};

static PortableServer_ServantBase__epv impl_CosNaming_BindingIterator_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_CosNaming_BindingIterator__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_CosNaming_BindingIterator__epv impl_CosNaming_BindingIterator_epv = {
    NULL, /* _private */
    (CORBA_boolean (*)(void *, CosNaming_Binding**, CORBA_Environment *))&impl_CosNaming_BindingIterator_next_one,
    (CORBA_boolean (*)(void *, CORBA_unsigned_long, CosNaming_BindingList**, CORBA_Environment *))&impl_CosNaming_BindingIterator_next_n,
    (void (*)(void *, CORBA_Environment *))&impl_CosNaming_BindingIterator_destroy,
};

static PortableServer_ServantBase__epv impl_CosNaming_NamingContextExt_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_CosNaming_NamingContextExt__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_CosNaming_NamingContextExt__epv impl_CosNaming_NamingContextExt_epv = {
    NULL, /* _private */
    (CosNaming_NamingContextExt_StringName (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContextExt_to_string,
    (CosNaming_Name* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_CosNaming_NamingContextExt_to_name,
    (CosNaming_NamingContextExt_URLString (*)(void *, const CORBA_char *, const CORBA_char *, CORBA_Environment *))&impl_CosNaming_NamingContextExt_to_url,
    (CORBA_Object (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_CosNaming_NamingContextExt_resolve_str,
};

static POA_CosNaming_NamingContext__epv impl_CosNaming_NamingContextExt_CosNaming_NamingContext_epv = 
{
     NULL, /* _private */
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_CosNaming_NamingContext__is_a,
    (void (*)(void *, CosNaming_Name*, CORBA_Object, CORBA_Environment *))&impl_CosNaming_NamingContext_bind,
    (void (*)(void *, CosNaming_Name*, CORBA_Object, CORBA_Environment *))&impl_CosNaming_NamingContext_rebind,
    (void (*)(void *, CosNaming_Name*, CosNaming_NamingContext, CORBA_Environment *))&impl_CosNaming_NamingContext_bind_context,
    (void (*)(void *, CosNaming_Name*, CosNaming_NamingContext, CORBA_Environment *))&impl_CosNaming_NamingContext_rebind_context,
    (CORBA_Object (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_resolve,
    (void (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_unbind,
    (CosNaming_NamingContext (*)(void *, CORBA_Environment *))&impl_CosNaming_NamingContext_new_context,
    (CosNaming_NamingContext (*)(void *, CosNaming_Name*, CORBA_Environment *))&impl_CosNaming_NamingContext_bind_new_context,
    (void (*)(void *, CORBA_Environment *))&impl_CosNaming_NamingContext_destroy,
    (void (*)(void *, CORBA_unsigned_long, CosNaming_BindingList**, CosNaming_BindingIterator*, CORBA_Environment *))&impl_CosNaming_NamingContext_list,
};


/*** vepv structures ***/
static POA_CosNaming_NamingContext__vepv impl_CosNaming_NamingContext_vepv = {
    &impl_CosNaming_NamingContext_base_epv,
    &impl_CosNaming_NamingContext_epv,
};

static POA_CosNaming_BindingIterator__vepv impl_CosNaming_BindingIterator_vepv = {
    &impl_CosNaming_BindingIterator_base_epv,
    &impl_CosNaming_BindingIterator_epv,
};

static POA_CosNaming_NamingContextExt__vepv impl_CosNaming_NamingContextExt_vepv = {
    &impl_CosNaming_NamingContextExt_base_epv,
    &impl_CosNaming_NamingContextExt_CosNaming_NamingContext_epv,
    &impl_CosNaming_NamingContextExt_epv,
};


/*** Stub implementations ***/
CORBA_CosNaming_NamingContext 
impl_CosNaming_NamingContext__create(PortableServer_POA poa, CORBA_Environment *ev)
{
  CORBA_CosNaming_NamingContext retval;
  impl_POA_CosNaming_NamingContext *newservant;
  PortableServer_ObjectId objid;

  newservant = (impl_POA_CosNaming_NamingContext *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_NamingContext)," create...");
  newservant->servant.vepv = &impl_CosNaming_NamingContext_vepv;
  newservant->poa = poa;
  POA_CosNaming_NamingContext__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

  objid = PortableServer_POA_activate_object(poa, newservant, ev);
  retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

  return retval;
}

void
impl_CosNaming_NamingContext__destroy(impl_POA_CosNaming_NamingContext *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

    POA_CosNaming_NamingContext__fini((PortableServer_Servant)servant, ev);

    RtORB_free (servant, "servant");
}



 /*** create servent **/ 
impl_POA_ServantBase * 
impl_CosNaming_NamingContext__create_servant(PortableServer_POA poa, CORBA_Environment *ev)
{
  impl_POA_CosNaming_NamingContext *newservant;

  newservant = (impl_POA_CosNaming_NamingContext *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_NamingContext), "  create_servant");
  newservant->servant.vepv = &impl_CosNaming_NamingContext_vepv;
  newservant->poa = poa;
  POA_CosNaming_NamingContext__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributs must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */


  return (impl_POA_ServantBase*)newservant;
}

CORBA_boolean
impl_CosNaming_NamingContext__is_a(
  impl_POA_CosNaming_NamingContext *servant,
  const CORBA_char * id,
  CORBA_Environment *ev)
{
  CORBA_boolean retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContext_bind(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CORBA_Object obj,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContext_rebind(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CORBA_Object obj,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContext_bind_context(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CosNaming_NamingContext nc,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContext_rebind_context(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CosNaming_NamingContext nc,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

CORBA_Object
impl_CosNaming_NamingContext_resolve(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CORBA_Environment *ev)
{
  CORBA_Object retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContext_unbind(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

CosNaming_NamingContext
impl_CosNaming_NamingContext_new_context(
  impl_POA_CosNaming_NamingContext *servant,
  CORBA_Environment *ev)
{
  CosNaming_NamingContext retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CosNaming_NamingContext
impl_CosNaming_NamingContext_bind_new_context(
  impl_POA_CosNaming_NamingContext *servant,
  CosNaming_Name* n,
  CORBA_Environment *ev)
{
  CosNaming_NamingContext retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContext_destroy(
  impl_POA_CosNaming_NamingContext *servant,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContext_list(
  impl_POA_CosNaming_NamingContext *servant,
  CORBA_unsigned_long how_many,
  CosNaming_BindingList** bl,
  CosNaming_BindingIterator* bi,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

CORBA_CosNaming_BindingIterator 
impl_CosNaming_BindingIterator__create(PortableServer_POA poa, CORBA_Environment *ev)
{
  CORBA_CosNaming_BindingIterator retval;
  impl_POA_CosNaming_BindingIterator *newservant;
  PortableServer_ObjectId objid;

  newservant = (impl_POA_CosNaming_BindingIterator *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_BindingIterator)," create...");
  newservant->servant.vepv = &impl_CosNaming_BindingIterator_vepv;
  newservant->poa = poa;
  POA_CosNaming_BindingIterator__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

  objid = PortableServer_POA_activate_object(poa, newservant, ev);
  retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

  return retval;
}

void
impl_CosNaming_BindingIterator__destroy(impl_POA_CosNaming_BindingIterator *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

    POA_CosNaming_BindingIterator__fini((PortableServer_Servant)servant, ev);

    RtORB_free (servant, "servant");
}



 /*** create servent **/ 
impl_POA_ServantBase * 
impl_CosNaming_BindingIterator__create_servant(PortableServer_POA poa, CORBA_Environment *ev)
{
  impl_POA_CosNaming_BindingIterator *newservant;

  newservant = (impl_POA_CosNaming_BindingIterator *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_BindingIterator), "  create_servant");
  newservant->servant.vepv = &impl_CosNaming_BindingIterator_vepv;
  newservant->poa = poa;
  POA_CosNaming_BindingIterator__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributs must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */


  return (impl_POA_ServantBase*)newservant;
}

CORBA_boolean
impl_CosNaming_BindingIterator_next_one(
  impl_POA_CosNaming_BindingIterator *servant,
  CosNaming_Binding** b,
  CORBA_Environment *ev)
{
  CORBA_boolean retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CORBA_boolean
impl_CosNaming_BindingIterator_next_n(
  impl_POA_CosNaming_BindingIterator *servant,
  CORBA_unsigned_long how_many,
  CosNaming_BindingList** bl,
  CORBA_Environment *ev)
{
  CORBA_boolean retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_BindingIterator_destroy(
  impl_POA_CosNaming_BindingIterator *servant,
  CORBA_Environment *ev)
{
    /* ------   insert method code here  (4) ------ */
    /* ------ ---------- end ------------ ------ */
}

CORBA_CosNaming_NamingContextExt 
impl_CosNaming_NamingContextExt__create(PortableServer_POA poa, CORBA_Environment *ev)
{
  CORBA_CosNaming_NamingContextExt retval;
  impl_POA_CosNaming_NamingContextExt *newservant;
  PortableServer_ObjectId objid;

  newservant = (impl_POA_CosNaming_NamingContextExt *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_NamingContextExt)," create...");
  newservant->servant.vepv = &impl_CosNaming_NamingContextExt_vepv;
  newservant->poa = poa;
  POA_CosNaming_NamingContextExt__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

  objid = PortableServer_POA_activate_object(poa, newservant, ev);
  retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

  return retval;
}

void
impl_CosNaming_NamingContextExt__destroy(impl_POA_CosNaming_NamingContextExt *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

    POA_CosNaming_NamingContextExt__fini((PortableServer_Servant)servant, ev);

    RtORB_free (servant, "servant");
}



 /*** create servent **/ 
impl_POA_ServantBase * 
impl_CosNaming_NamingContextExt__create_servant(PortableServer_POA poa, CORBA_Environment *ev)
{
  impl_POA_CosNaming_NamingContextExt *newservant;

  newservant = (impl_POA_CosNaming_NamingContextExt *)RtORB_calloc(1, sizeof(impl_POA_CosNaming_NamingContextExt), "  create_servant");
  newservant->servant.vepv = &impl_CosNaming_NamingContextExt_vepv;
  newservant->poa = poa;
  POA_CosNaming_NamingContextExt__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributs must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */


  return (impl_POA_ServantBase*)newservant;
}

CosNaming_NamingContextExt_StringName
impl_CosNaming_NamingContextExt_to_string(
  impl_POA_CosNaming_NamingContextExt *servant,
  CosNaming_Name* n,
  CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_StringName retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CosNaming_Name*
impl_CosNaming_NamingContextExt_to_name(
  impl_POA_CosNaming_NamingContextExt *servant,
  const CORBA_char * sn,
  CORBA_Environment *ev)
{
  CosNaming_Name* retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CosNaming_NamingContextExt_URLString
impl_CosNaming_NamingContextExt_to_url(
  impl_POA_CosNaming_NamingContextExt *servant,
  const CORBA_char * addr,
  const CORBA_char * sn,
  CORBA_Environment *ev)
{
  CosNaming_NamingContextExt_URLString retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CORBA_Object
impl_CosNaming_NamingContextExt_resolve_str(
  impl_POA_CosNaming_NamingContextExt *servant,
  const CORBA_char * n,
  CORBA_Environment *ev)
{
  CORBA_Object retval;
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here (2)  ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CORBA_boolean
impl_CosNaming_NamingContextExt__is_a(
    impl_POA_CosNaming_NamingContextExt *servant,
    const CORBA_char * id,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
  CORBA_boolean retval;
    /* ------   insert method code here  (6) ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContextExt_bind(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CORBA_Object obj,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContextExt_rebind(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CORBA_Object obj,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContextExt_bind_context(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CosNaming_NamingContext nc,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContextExt_rebind_context(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CosNaming_NamingContext nc,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

CORBA_Object
impl_CosNaming_NamingContextExt_resolve(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
  CORBA_Object retval;
    /* ------   insert method code here  (6) ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContextExt_unbind(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

CosNaming_NamingContext
impl_CosNaming_NamingContextExt_new_context(
    impl_POA_CosNaming_NamingContextExt *servant,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
  CosNaming_NamingContext retval;
    /* ------   insert method code here  (6) ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

CosNaming_NamingContext
impl_CosNaming_NamingContextExt_bind_new_context(
    impl_POA_CosNaming_NamingContextExt *servant,
    CosNaming_Name* n,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
  CosNaming_NamingContext retval;
    /* ------   insert method code here  (6) ------ */
    /* ------ ---------- end ------------ ------ */

  return retval;
}

void
impl_CosNaming_NamingContextExt_destroy(
    impl_POA_CosNaming_NamingContextExt *servant,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}

void
impl_CosNaming_NamingContextExt_list(
    impl_POA_CosNaming_NamingContextExt *servant,
    CORBA_unsigned_long how_many,
    CosNaming_BindingList** bl,
    CosNaming_BindingIterator* bi,
    CORBA_Environment *ev)
{
  memset(ev, 0, sizeof(CORBA_Environment));
    /* ------   insert method code here   (7)------ */
    /* ------ ---------- end ------------ ------ */
}


/*** Boohoo! ***/
