/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#include <RtORB/cdrStream.h>
#define CONST const
#define CosNaming_COMMON
#include "CosNaming.h"

/** Interface Module definitions in CosNaming */

#ifndef ORBIT_IDL_C_IMODULE_CosNaming
/* List (Skels) */
/* Module (Skels) */
/* List (Skels) */
/* Interface declarations (Skels) */
/* List (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext__is_a(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_boolean (*_impl__is_a)(PortableServer_Servant _servant, const CORBA_char * id, CORBA_Environment *ev))
{
  *(CORBA_boolean *)result = _impl__is_a (obj, *(const CORBA_char * *)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_bind(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_bind)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev))
{
  _impl_bind (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], *(CORBA_Object *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_rebind(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_rebind)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Object obj, CORBA_Environment *ev))
{
  _impl_rebind (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], *(CORBA_Object *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_bind_context(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_bind_context)(PortableServer_Servant _servant, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev))
{
  _impl_bind_context (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], *(CosNaming_NamingContext *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_rebind_context(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_rebind_context)(PortableServer_Servant _servant, CosNaming_Name* n, CosNaming_NamingContext nc, CORBA_Environment *ev))
{
  _impl_rebind_context (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], *(CosNaming_NamingContext *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_resolve(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_Object (*_impl_resolve)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Environment *ev))
{
  *(CORBA_Object *)result = _impl_resolve (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_unbind(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_unbind)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Environment *ev))
{
  _impl_unbind (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_new_context(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CosNaming_NamingContext (*_impl_new_context)(PortableServer_Servant _servant, CORBA_Environment *ev))
{
  *(CosNaming_NamingContext *)result = _impl_new_context (obj, env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_bind_new_context(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CosNaming_NamingContext (*_impl_bind_new_context)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Environment *ev))
{
  *(CosNaming_NamingContext *)result = _impl_bind_new_context (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_destroy(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_destroy)(PortableServer_Servant _servant, CORBA_Environment *ev))
{
  _impl_destroy (obj, env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContext_list(CORBA_CosNaming_NamingContext obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_list)(PortableServer_Servant _servant, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CosNaming_BindingIterator* bi, CORBA_Environment *ev))
{
  _impl_list (obj, *(CORBA_unsigned_long *)argv[0], (CORBA_sequence_CosNaming_Binding**)argv[1], *(CosNaming_BindingIterator* *)argv[2], env);
}
/* End of Option declarations (Skels) */
/* End of List (Skels) */
/* End of Interface declarations (Skels) */
/* Interface declarations (Skels) */
/* List (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_BindingIterator_next_one(CORBA_CosNaming_BindingIterator obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_boolean (*_impl_next_one)(PortableServer_Servant _servant, CosNaming_Binding** b, CORBA_Environment *ev))
{
  *(CORBA_boolean *)result = _impl_next_one (obj, (CosNaming_Binding**)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_BindingIterator_next_n(CORBA_CosNaming_BindingIterator obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_boolean (*_impl_next_n)(PortableServer_Servant _servant, CORBA_unsigned_long how_many, CosNaming_BindingList** bl, CORBA_Environment *ev))
{
  *(CORBA_boolean *)result = _impl_next_n (obj, *(CORBA_unsigned_long *)argv[0], (CORBA_sequence_CosNaming_Binding**)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_BindingIterator_destroy(CORBA_CosNaming_BindingIterator obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_destroy)(PortableServer_Servant _servant, CORBA_Environment *ev))
{
  _impl_destroy (obj, env);
}
/* End of Option declarations (Skels) */
/* End of List (Skels) */
/* End of Interface declarations (Skels) */
/* Interface declarations (Skels) */
/* List (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContextExt_to_string(CORBA_CosNaming_NamingContextExt obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CosNaming_NamingContextExt_StringName (*_impl_to_string)(PortableServer_Servant _servant, CosNaming_Name* n, CORBA_Environment *ev))
{
  *(CosNaming_NamingContextExt_StringName *)result = _impl_to_string (obj, (CORBA_sequence_CosNaming_NameComponent*)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContextExt_to_name(CORBA_CosNaming_NamingContextExt obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CosNaming_Name* (*_impl_to_name)(PortableServer_Servant _servant, const CORBA_char * sn, CORBA_Environment *ev))
{
  *(CosNaming_Name* *)result = _impl_to_name (obj, *(const CORBA_char * *)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContextExt_to_url(CORBA_CosNaming_NamingContextExt obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CosNaming_NamingContextExt_URLString (*_impl_to_url)(PortableServer_Servant _servant, const CORBA_char * addr, const CORBA_char * sn, CORBA_Environment *ev))
{
  *(CosNaming_NamingContextExt_URLString *)result = _impl_to_url (obj, *(const CORBA_char * *)argv[0], *(const CORBA_char * *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_CosNaming_NamingContextExt_resolve_str(CORBA_CosNaming_NamingContextExt obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_Object (*_impl_resolve_str)(PortableServer_Servant _servant, const CORBA_char * n, CORBA_Environment *ev))
{
  *(CORBA_Object *)result = _impl_resolve_str (obj, *(const CORBA_char * *)argv[0], env);
}
/* End of Option declarations (Skels) */
/* End of List (Skels) */
/* End of Interface declarations (Skels) */
/* End of List (Skels) */
/* End of Module (Skels) */
/* End of List (Skels) */

#endif

/** TypeCode definitions in CosNaming */
/*  TypeCode in C (anonTC_0) */
/*  TypeCode in C (TC_CosNaming_Istring) */
#if  (TC_IMPL_TC_CosNaming_Istring == 1)   && !defined(TC_DEF_TC_CosNaming_Istring)
#define TC_DEF_TC_CosNaming_Istring 1
static const CORBA_TypeCode anon_subtypes_array5[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CosNaming_Istring  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_Istring_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/Istring:1.0",  /* repository_id */
  (char *)"Istring",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array5,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NameComponent) */
#if  (TC_IMPL_TC_CosNaming_NameComponent == 1)   && !defined(TC_DEF_TC_CosNaming_NameComponent)
#define TC_DEF_TC_CosNaming_NameComponent 1
static const char *anon_subnames_array7[] = {"id", "kind"};
static const CORBA_TypeCode anon_subtypes_array8[] = {
    (CORBA_TypeCode)&TC_CosNaming_Istring_struct,
    (CORBA_TypeCode)&TC_CosNaming_Istring_struct};
/***   TC_CosNaming_NameComponent  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NameComponent_struct = {
  NULL, /* parent */
  tk_struct,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NameComponent:1.0",  /* repository_id */
  (char *)"NameComponent",  /* identifier */
  2,    /* member_count  */
  (char **)anon_subnames_array7,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array8,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (TC_CORBA_sequence_CosNaming_NameComponent) */
#if  (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent)
#define TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent 1
static const CORBA_TypeCode anon_subtypes_array11[] = { (CORBA_TypeCode)&TC_CosNaming_NameComponent_struct };
/***   TC_CORBA_sequence_CosNaming_NameComponent  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_NameComponent_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array11,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_13) */
/*  TypeCode in C (TC_CORBA_sequence_CosNaming_NameComponent) */
#if  (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent)
#define TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent 1
static const CORBA_TypeCode anon_subtypes_array18[] = { (CORBA_TypeCode)&TC_CosNaming_NameComponent_struct };
/***   TC_CORBA_sequence_CosNaming_NameComponent  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_NameComponent_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array18,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_Name) */
#if  (TC_IMPL_TC_CosNaming_Name == 1)   && !defined(TC_DEF_TC_CosNaming_Name)
#define TC_DEF_TC_CosNaming_Name 1
static const CORBA_TypeCode anon_subtypes_array21[] = { (CORBA_TypeCode)&TC_CORBA_sequence_CosNaming_NameComponent_struct };
/***   TC_CosNaming_Name  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_Name_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/Name:1.0",  /* repository_id */
  (char *)"Name",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array21,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_BindingType) */
#if  (TC_IMPL_TC_CosNaming_BindingType == 1)   && !defined(TC_DEF_TC_CosNaming_BindingType)
#define TC_DEF_TC_CosNaming_BindingType 1
static const char *anon_subnames_array23[] = {"nobject", "ncontext"};
/***   TC_CosNaming_BindingType  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_BindingType_struct = {
  NULL, /* parent */
  tk_enum,  /* kind */
  (char *)"IDL:omg.org/CosNaming/BindingType:1.0",  /* repository_id */
  (char *)"BindingType",  /* identifier */
  2,    /* member_count  */
  (char **)anon_subnames_array23,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_long    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_Binding) */
#if  (TC_IMPL_TC_CosNaming_Binding == 1)   && !defined(TC_DEF_TC_CosNaming_Binding)
#define TC_DEF_TC_CosNaming_Binding 1
static const char *anon_subnames_array26[] = {"binding_name", "binding_type"};
static const CORBA_TypeCode anon_subtypes_array27[] = {
    (CORBA_TypeCode)&TC_CosNaming_Name_struct,
    (CORBA_TypeCode)&TC_CosNaming_BindingType_struct};
/***   TC_CosNaming_Binding  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_Binding_struct = {
  NULL, /* parent */
  tk_struct,  /* kind */
  (char *)"IDL:omg.org/CosNaming/Binding:1.0",  /* repository_id */
  (char *)"Binding",  /* identifier */
  2,    /* member_count  */
  (char **)anon_subnames_array26,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array27,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CORBA_sequence_CosNaming_Binding) */
#if  (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_Binding)
#define TC_DEF_TC_CORBA_sequence_CosNaming_Binding 1
static const CORBA_TypeCode anon_subtypes_array30[] = { (CORBA_TypeCode)&TC_CosNaming_Binding_struct };
/***   TC_CORBA_sequence_CosNaming_Binding  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_Binding_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array30,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_32) */
/*  TypeCode in C (TC_CORBA_sequence_CosNaming_Binding) */
#if  (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_Binding)
#define TC_DEF_TC_CORBA_sequence_CosNaming_Binding 1
static const CORBA_TypeCode anon_subtypes_array37[] = { (CORBA_TypeCode)&TC_CosNaming_Binding_struct };
/***   TC_CORBA_sequence_CosNaming_Binding  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_Binding_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array37,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_BindingList) */
#if  (TC_IMPL_TC_CosNaming_BindingList == 1)   && !defined(TC_DEF_TC_CosNaming_BindingList)
#define TC_DEF_TC_CosNaming_BindingList 1
static const CORBA_TypeCode anon_subtypes_array40[] = { (CORBA_TypeCode)&TC_CORBA_sequence_CosNaming_Binding_struct };
/***   TC_CosNaming_BindingList  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_BindingList_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/BindingList:1.0",  /* repository_id */
  (char *)"BindingList",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array40,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_NotFoundReason) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_NotFoundReason)
#define TC_DEF_TC_CosNaming_NamingContext_NotFoundReason 1
static const char *anon_subnames_array42[] = {"missing_node", "not_context", "not_object"};
/***   TC_CosNaming_NamingContext_NotFoundReason  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_NotFoundReason_struct = {
  NULL, /* parent */
  tk_enum,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0",  /* repository_id */
  (char *)"NotFoundReason",  /* identifier */
  3,    /* member_count  */
  (char **)anon_subnames_array42,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_long    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_NotFound) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_NotFound == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_NotFound)
#define TC_DEF_TC_CosNaming_NamingContext_NotFound 1
static const char *anon_subnames_array45[] = {"why", "rest_of_name"};
static const CORBA_TypeCode anon_subtypes_array46[] = {
    (CORBA_TypeCode)&TC_CosNaming_NamingContext_NotFoundReason_struct,
    (CORBA_TypeCode)&TC_CosNaming_Name_struct};
/***   TC_CosNaming_NamingContext_NotFound  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_NotFound_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/NotFound:1.0",  /* repository_id */
  (char *)"NotFound",  /* identifier */
  2,    /* member_count  */
  (char **)anon_subnames_array45,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array46,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_sequence, MAX (Align_long, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_CannotProceed) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_CannotProceed)
#define TC_DEF_TC_CosNaming_NamingContext_CannotProceed 1
static const char *anon_subnames_array48[] = {"cxt", "rest_of_name"};
static const CORBA_TypeCode anon_subtypes_array49[] = {
    (CORBA_TypeCode)&TC_CosNaming_NamingContext_struct,
    (CORBA_TypeCode)&TC_CosNaming_Name_struct};
/***   TC_CosNaming_NamingContext_CannotProceed  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_CannotProceed_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/CannotProceed:1.0",  /* repository_id */
  (char *)"CannotProceed",  /* identifier */
  2,    /* member_count  */
  (char **)anon_subnames_array48,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array49,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_long, MAX (Align_sequence, MAX (Align_pointer, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_InvalidName) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_InvalidName == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_InvalidName)
#define TC_DEF_TC_CosNaming_NamingContext_InvalidName 1
/***   TC_CosNaming_NamingContext_InvalidName  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_InvalidName_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0",  /* repository_id */
  (char *)"InvalidName",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  1    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_AlreadyBound) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_AlreadyBound)
#define TC_DEF_TC_CosNaming_NamingContext_AlreadyBound 1
/***   TC_CosNaming_NamingContext_AlreadyBound  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_AlreadyBound_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",  /* repository_id */
  (char *)"AlreadyBound",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  1    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext_NotEmpty) */
#if  (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext_NotEmpty)
#define TC_DEF_TC_CosNaming_NamingContext_NotEmpty 1
/***   TC_CosNaming_NamingContext_NotEmpty  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_NotEmpty_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",  /* repository_id */
  (char *)"NotEmpty",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  1    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContext) */
#if  (TC_IMPL_TC_CosNaming_NamingContext == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContext)
#define TC_DEF_TC_CosNaming_NamingContext 1
/***   TC_CosNaming_NamingContext  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_struct = {
  NULL, /* parent */
  tk_objref,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContext:1.0",  /* repository_id */
  (char *)"NamingContext",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_BindingIterator) */
#if  (TC_IMPL_TC_CosNaming_BindingIterator == 1)   && !defined(TC_DEF_TC_CosNaming_BindingIterator)
#define TC_DEF_TC_CosNaming_BindingIterator 1
/***   TC_CosNaming_BindingIterator  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_BindingIterator_struct = {
  NULL, /* parent */
  tk_objref,  /* kind */
  (char *)"IDL:omg.org/CosNaming/BindingIterator:1.0",  /* repository_id */
  (char *)"BindingIterator",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_66) */
/*  TypeCode in C (TC_CosNaming_NamingContextExt_StringName) */
#if  (TC_IMPL_TC_CosNaming_NamingContextExt_StringName == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContextExt_StringName)
#define TC_DEF_TC_CosNaming_NamingContextExt_StringName 1
static const CORBA_TypeCode anon_subtypes_array71[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CosNaming_NamingContextExt_StringName  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContextExt_StringName_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContextExt/StringName:1.0",  /* repository_id */
  (char *)"StringName",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array71,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_73) */
/*  TypeCode in C (TC_CosNaming_NamingContextExt_Address) */
#if  (TC_IMPL_TC_CosNaming_NamingContextExt_Address == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContextExt_Address)
#define TC_DEF_TC_CosNaming_NamingContextExt_Address 1
static const CORBA_TypeCode anon_subtypes_array78[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CosNaming_NamingContextExt_Address  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContextExt_Address_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContextExt/Address:1.0",  /* repository_id */
  (char *)"Address",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array78,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_80) */
/*  TypeCode in C (TC_CosNaming_NamingContextExt_URLString) */
#if  (TC_IMPL_TC_CosNaming_NamingContextExt_URLString == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContextExt_URLString)
#define TC_DEF_TC_CosNaming_NamingContextExt_URLString 1
static const CORBA_TypeCode anon_subtypes_array85[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CosNaming_NamingContextExt_URLString  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContextExt_URLString_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContextExt/URLString:1.0",  /* repository_id */
  (char *)"URLString",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array85,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContextExt_InvalidAddress) */
#if  (TC_IMPL_TC_CosNaming_NamingContextExt_InvalidAddress == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContextExt_InvalidAddress)
#define TC_DEF_TC_CosNaming_NamingContextExt_InvalidAddress 1
/***   TC_CosNaming_NamingContextExt_InvalidAddress  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContextExt_InvalidAddress_struct = {
  NULL, /* parent */
  tk_except,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0",  /* repository_id */
  (char *)"InvalidAddress",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  1    /* alignment */

};
#endif

/*  TypeCode in C (TC_CosNaming_NamingContextExt) */
#if  (TC_IMPL_TC_CosNaming_NamingContextExt == 1)   && !defined(TC_DEF_TC_CosNaming_NamingContextExt)
#define TC_DEF_TC_CosNaming_NamingContextExt 1
/***   TC_CosNaming_NamingContextExt  ***/

#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
struct CORBA_TypeCode_struct TC_CosNaming_NamingContextExt_struct = {
  NULL, /* parent */
  tk_objref,  /* kind */
  (char *)"IDL:omg.org/CosNaming/NamingContextExt:1.0",  /* repository_id */
  (char *)"NamingContextExt",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif


/** Class ID definitions in CosNaming */

#ifndef ORBIT_IDL_C_IMODULE_CosNaming
CORBA_unsigned_long CosNaming_NamingContext__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_CosNaming
CORBA_unsigned_long CosNaming_BindingIterator__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_CosNaming
CORBA_unsigned_long CosNaming_NamingContextExt__classid = 0;
#endif

/* Interface type data */

static CORBA_IArg CosNaming_NamingContext__is_a__arginfo [] = {
	{ TC_CORBA_string,  CORBA_I_ARG_IN , (char *)"id" }
};
static CORBA_IArg CosNaming_NamingContext_bind__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" },
	{ TC_CORBA_Object,  CORBA_I_ARG_IN , (char *)"obj" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_bind__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	TC_CosNaming_NamingContext_AlreadyBound,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_rebind__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" },
	{ TC_CORBA_Object,  CORBA_I_ARG_IN , (char *)"obj" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_rebind__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_bind_context__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" },
	{ TC_CosNaming_NamingContext,  CORBA_I_ARG_IN , (char *)"nc" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_bind_context__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	TC_CosNaming_NamingContext_AlreadyBound,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_rebind_context__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" },
	{ TC_CosNaming_NamingContext,  CORBA_I_ARG_IN , (char *)"nc" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_rebind_context__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_resolve__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_resolve__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_unbind__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_unbind__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_bind_new_context__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_bind_new_context__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	TC_CosNaming_NamingContext_AlreadyBound,
	NULL
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContext_destroy__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotEmpty,
	NULL
};
static CORBA_IArg CosNaming_NamingContext_list__arginfo [] = {
	{ TC_CORBA_unsigned_long,  CORBA_I_ARG_IN , (char *)"how_many" },
	{ TC_CosNaming_BindingList,  CORBA_I_ARG_OUT , (char *)"bl" },
	{ TC_CosNaming_BindingIterator,  CORBA_I_ARG_OUT , (char *)"bi" }
};
CORBA_Class_Method CosNaming_NamingContext__methods [] = {
	{
		(char *)"_is_a",
		TC_CORBA_boolean, 
		 1, CosNaming_NamingContext__is_a__arginfo,  
		 0, NULL

	},	{
		(char *)"bind",
TC_void, 
		 2, CosNaming_NamingContext_bind__arginfo,  
		 4, CosNaming_NamingContext_bind__exceptinfo 

	},	{
		(char *)"rebind",
TC_void, 
		 2, CosNaming_NamingContext_rebind__arginfo,  
		 3, CosNaming_NamingContext_rebind__exceptinfo 

	},	{
		(char *)"bind_context",
TC_void, 
		 2, CosNaming_NamingContext_bind_context__arginfo,  
		 4, CosNaming_NamingContext_bind_context__exceptinfo 

	},	{
		(char *)"rebind_context",
TC_void, 
		 2, CosNaming_NamingContext_rebind_context__arginfo,  
		 3, CosNaming_NamingContext_rebind_context__exceptinfo 

	},	{
		(char *)"resolve",
		TC_CORBA_Object, 
		 1, CosNaming_NamingContext_resolve__arginfo,  
		 3, CosNaming_NamingContext_resolve__exceptinfo 

	},	{
		(char *)"unbind",
TC_void, 
		 1, CosNaming_NamingContext_unbind__arginfo,  
		 3, CosNaming_NamingContext_unbind__exceptinfo 

	},	{
		(char *)"new_context",
		TC_CosNaming_NamingContext, 
		 0, NULL, 
		 0, NULL

	},	{
		(char *)"bind_new_context",
		TC_CosNaming_NamingContext, 
		 1, CosNaming_NamingContext_bind_new_context__arginfo,  
		 4, CosNaming_NamingContext_bind_new_context__exceptinfo 

	},	{
		(char *)"destroy",
TC_void, 
		 0, NULL, 
		 1, CosNaming_NamingContext_destroy__exceptinfo 

	},	{
		(char *)"list",
TC_void, 
		 3, CosNaming_NamingContext_list__arginfo,  
		 0, NULL

	}
};
static char * CosNaming_NamingContext__base_itypes[] = {
	(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
CORBA_Class_Impl CosNaming_NamingContext__imp = {
    TC_CosNaming_NamingContext,
    (char *)"CosNaming_NamingContext",
    11,
    CosNaming_NamingContext__methods,
    1, (char **) CosNaming_NamingContext__base_itypes
};

static CORBA_IArg CosNaming_BindingIterator_next_one__arginfo [] = {
	{ TC_CosNaming_Binding,  CORBA_I_ARG_OUT , (char *)"b" }
};
static CORBA_IArg CosNaming_BindingIterator_next_n__arginfo [] = {
	{ TC_CORBA_unsigned_long,  CORBA_I_ARG_IN , (char *)"how_many" },
	{ TC_CosNaming_BindingList,  CORBA_I_ARG_OUT , (char *)"bl" }
};
CORBA_Class_Method CosNaming_BindingIterator__methods [] = {
	{
		(char *)"next_one",
		TC_CORBA_boolean, 
		 1, CosNaming_BindingIterator_next_one__arginfo,  
		 0, NULL

	},	{
		(char *)"next_n",
		TC_CORBA_boolean, 
		 2, CosNaming_BindingIterator_next_n__arginfo,  
		 0, NULL

	},	{
		(char *)"destroy",
TC_void, 
		 0, NULL, 
		 0, NULL

	}
};
static char * CosNaming_BindingIterator__base_itypes[] = {
	(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
CORBA_Class_Impl CosNaming_BindingIterator__imp = {
    TC_CosNaming_BindingIterator,
    (char *)"CosNaming_BindingIterator",
    3,
    CosNaming_BindingIterator__methods,
    1, (char **) CosNaming_BindingIterator__base_itypes
};

static CORBA_IArg CosNaming_NamingContextExt_to_string__arginfo [] = {
	{ TC_CosNaming_Name,  CORBA_I_ARG_IN , (char *)"n" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContextExt_to_string__exceptinfo [] = {
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContextExt_to_name__arginfo [] = {
	{ TC_CosNaming_NamingContextExt_StringName,  CORBA_I_ARG_IN , (char *)"sn" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContextExt_to_name__exceptinfo [] = {
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContextExt_to_url__arginfo [] = {
	{ TC_CosNaming_NamingContextExt_Address,  CORBA_I_ARG_IN , (char *)"addr" },
	{ TC_CosNaming_NamingContextExt_StringName,  CORBA_I_ARG_IN , (char *)"sn" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContextExt_to_url__exceptinfo [] = {
	TC_CosNaming_NamingContextExt_InvalidAddress,
	TC_CosNaming_NamingContext_InvalidName,
	NULL
};
static CORBA_IArg CosNaming_NamingContextExt_resolve_str__arginfo [] = {
	{ TC_CosNaming_NamingContextExt_StringName,  CORBA_I_ARG_IN , (char *)"n" }
};
/* Exceptions */
static CORBA_TypeCode CosNaming_NamingContextExt_resolve_str__exceptinfo [] = {
	TC_CosNaming_NamingContext_NotFound,
	TC_CosNaming_NamingContext_CannotProceed,
	TC_CosNaming_NamingContext_InvalidName,
	TC_CosNaming_NamingContext_AlreadyBound,
	NULL
};
CORBA_Class_Method CosNaming_NamingContextExt__methods [] = {
	{
		(char *)"to_string",
		TC_CosNaming_NamingContextExt_StringName, 
		 1, CosNaming_NamingContextExt_to_string__arginfo,  
		 1, CosNaming_NamingContextExt_to_string__exceptinfo 

	},	{
		(char *)"to_name",
		TC_CosNaming_Name, 
		 1, CosNaming_NamingContextExt_to_name__arginfo,  
		 1, CosNaming_NamingContextExt_to_name__exceptinfo 

	},	{
		(char *)"to_url",
		TC_CosNaming_NamingContextExt_URLString, 
		 2, CosNaming_NamingContextExt_to_url__arginfo,  
		 2, CosNaming_NamingContextExt_to_url__exceptinfo 

	},	{
		(char *)"resolve_str",
		TC_CORBA_Object, 
		 1, CosNaming_NamingContextExt_resolve_str__arginfo,  
		 4, CosNaming_NamingContextExt_resolve_str__exceptinfo 

	}
};
static char * CosNaming_NamingContextExt__base_itypes[] = {
	(char *)"IDL:omg.org/CosNaming/NamingContext:1.0",
	(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_CosNaming
static
#endif
CORBA_Class_Impl CosNaming_NamingContextExt__imp = {
    TC_CosNaming_NamingContextExt,
    (char *)"CosNaming_NamingContextExt",
    4,
    CosNaming_NamingContextExt__methods,
    2, (char **) CosNaming_NamingContextExt__base_itypes
};

/* C++ Methods */
#ifdef __cplusplus /* cc_output_methods */
#ifndef Defined_cdr_CosNaming_NameComponent
#define Defined_cdr_CosNaming_NameComponent TRUE
 void CosNaming_NameComponent::operator>>=(cdrStream &_n) CONST 
{
  id >>= _n;
  kind >>= _n;
}
 void CosNaming_NameComponent::operator<<=(cdrStream &_n) {
  id <<= _n;
  kind <<= _n;
}
#endif /* Defined_cdr_CosNaming_NameComponent */
#ifndef Defined_CORBA_sequence_CosNaming_NameComponent
#define Defined_CORBA_sequence_CosNaming_NameComponent TRUE
 CORBA_sequence_CosNaming_NameComponent::CppSeq::ElemRef 
CORBA_sequence_CosNaming_NameComponent::operator[](CORBA::ULong n)
{
  return CORBA_sequence_CosNaming_NameComponent::CppSeq::element(this, (int)n);
}

 CORBA_sequence_CosNaming_NameComponent::CppSeq::ElemRef 
CORBA_sequence_CosNaming_NameComponent::operator[](CORBA::ULong n) const
{
  return CORBA_sequence_CosNaming_NameComponent::CppSeq::element(this, (int)n );
}

 CORBA::ULong 
CORBA_sequence_CosNaming_NameComponent::length(CORBA::ULong n)
{
  return CORBA_sequence_CosNaming_NameComponent::CppSeq::length(this, n);
}

 CORBA_sequence_CosNaming_NameComponent_type & 
CORBA_sequence_CosNaming_NameComponent::operator=(const CppSeq &o)
{
  o.copyTo(*this);
  return *this;
}

 CORBA_sequence_CosNaming_NameComponent_type & 
CORBA_sequence_CosNaming_NameComponent::operator=(const CORBA_sequence_CosNaming_NameComponent_type &o)
{
  CppSeq::copy(o, *this);
  return *this;
}

#endif /* Defined_CORBA_sequence_CosNaming_NameComponent */
#ifndef Defined_cdr_CosNaming_Binding
#define Defined_cdr_CosNaming_Binding TRUE
 void CosNaming_Binding::operator>>=(cdrStream &_n) CONST 
{
  binding_name >>= _n;
  binding_type >>= _n;
}
 void CosNaming_Binding::operator<<=(cdrStream &_n) {
  binding_name <<= _n;
  binding_type <<= _n;
}
#endif /* Defined_cdr_CosNaming_Binding */
#ifndef Defined_CORBA_sequence_CosNaming_Binding
#define Defined_CORBA_sequence_CosNaming_Binding TRUE
 CORBA_sequence_CosNaming_Binding::CppSeq::ElemRef 
CORBA_sequence_CosNaming_Binding::operator[](CORBA::ULong n)
{
  return CORBA_sequence_CosNaming_Binding::CppSeq::element(this, (int)n);
}

 CORBA_sequence_CosNaming_Binding::CppSeq::ElemRef 
CORBA_sequence_CosNaming_Binding::operator[](CORBA::ULong n) const
{
  return CORBA_sequence_CosNaming_Binding::CppSeq::element(this, (int)n );
}

 CORBA::ULong 
CORBA_sequence_CosNaming_Binding::length(CORBA::ULong n)
{
  return CORBA_sequence_CosNaming_Binding::CppSeq::length(this, n);
}

 CORBA_sequence_CosNaming_Binding_type & 
CORBA_sequence_CosNaming_Binding::operator=(const CppSeq &o)
{
  o.copyTo(*this);
  return *this;
}

 CORBA_sequence_CosNaming_Binding_type & 
CORBA_sequence_CosNaming_Binding::operator=(const CORBA_sequence_CosNaming_Binding_type &o)
{
  CppSeq::copy(o, *this);
  return *this;
}

#endif /* Defined_CORBA_sequence_CosNaming_Binding */
#endif /* __cplusplus */
