/* This is a template file generated by command */
/* rtorb-idl --skeleton-impl OpenRTM-aist.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

/*
 * Copyright (c) 2012, AIST.
 * All rights reserved. This program is made available under the terms of the
 * Eclipse Public License v1.0 which accompanies this distribution, and is
 * available at http://www.eclipse.org/legal/epl-v10.html
 * Contributors:
 * National Institute of Advanced Industrial Science and Technology (AIST)
 */
/*!
 * \file OpenRTM-aist-skelimpl.c
 * \brief IDLに記述された各種データやInterfaceがIDL-Compilerによりgenerateされ、各種servantの生成や削除、各InterfaceのPOAオブジェクト定義とメソッドを関数として実装などを行う。 <BR>
 *        IDL-Compilerでgenerateした際には、当ファイル内に、全てのInterfaceの情報が記述されているが、1ファイルのコード量が多く煩雑なため、Interface毎にファイルを分割(impl/Impl_???.c)し、当ファイルの最下方にて、それらをincludeするようにしている。
 * \author National Institute of Advanced Industrial Science and Technology (AIST)
 */

#include "OpenRTM-aist-skelimpl.h"

/*** epv structures ***/
static PortableServer_ServantBase__epv impl_SDOPackage_SDOSystemElement_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_SDOSystemElement__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_SDOSystemElement__epv impl_SDOPackage_SDOSystemElement_epv = {
    NULL, /* _private */
    (SDOPackage_OrganizationList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDOSystemElement_get_owned_organizations,
};

static PortableServer_ServantBase__epv impl_SDOPackage_SDO_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_SDO__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_SDO__epv impl_SDOPackage_SDO_epv = {
    NULL, /* _private */
    (SDOPackage_UniqueIdentifier (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_id,
    (CORBA_string (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_type,
    (SDOPackage_DeviceProfile* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_device_profile,
    (SDOPackage_ServiceProfileList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_service_profiles,
    (SDOPackage_ServiceProfile* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_service_profile,
    (SDOPackage_SDOService (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_service,
    (SDOPackage_Monitoring (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_monitoring,
    (SDOPackage_OrganizationList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_organizations,
    (SDOPackage_NVList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_status_list,
    (CORBA_any* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_status,
    (SDOPackage_Configuration (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_configuration,
};

static POA_SDOPackage_SDOSystemElement__epv impl_SDOPackage_SDO_SDOPackage_SDOSystemElement_epv = 
{
     NULL, /* _private */
    (SDOPackage_OrganizationList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDOSystemElement_get_owned_organizations,
};

static PortableServer_ServantBase__epv impl_SDOPackage_Configuration_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_Configuration__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_Configuration__epv impl_SDOPackage_Configuration_epv = {
    NULL, /* _private */
    (CORBA_boolean (*)(void *, SDOPackage_DeviceProfile*, CORBA_Environment *))&impl_SDOPackage_Configuration_set_device_profile,
    (CORBA_boolean (*)(void *, SDOPackage_ServiceProfile*, CORBA_Environment *))&impl_SDOPackage_Configuration_add_service_profile,
    (CORBA_boolean (*)(void *, SDOPackage_Organization, CORBA_Environment *))&impl_SDOPackage_Configuration_add_organization,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_remove_service_profile,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_remove_organization,
    (SDOPackage_ParameterList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_configuration_parameters,
    (SDOPackage_NVList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_configuration_parameter_values,
    (CORBA_any* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_configuration_parameter_value,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_any*, CORBA_Environment *))&impl_SDOPackage_Configuration_set_configuration_parameter,
    (SDOPackage_ConfigurationSet* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_configuration_set,
    (CORBA_boolean (*)(void *, SDOPackage_ConfigurationSet*, CORBA_Environment *))&impl_SDOPackage_Configuration_set_configuration_set_values,
    (CORBA_boolean (*)(void *, SDOPackage_ConfigurationSet*, CORBA_Environment *))&impl_SDOPackage_Configuration_add_configuration_set,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_remove_configuration_set,
    (SDOPackage_ConfigurationSetList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_configuration_sets,
    (SDOPackage_ConfigurationSet* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Configuration_get_active_configuration_set,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Configuration_activate_configuration_set,
};

static PortableServer_ServantBase__epv impl_SDOPackage_Monitoring_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_Monitoring__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_Monitoring__epv impl_SDOPackage_Monitoring_epv = {
    NULL, /* _private */
};

static PortableServer_ServantBase__epv impl_SDOPackage_SDOService_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_SDOService__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_SDOService__epv impl_SDOPackage_SDOService_epv = {
    NULL, /* _private */
};

static PortableServer_ServantBase__epv impl_SDOPackage_Organization_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_SDOPackage_Organization__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_SDOPackage_Organization__epv impl_SDOPackage_Organization_epv = {
    NULL, /* _private */
    (SDOPackage_UniqueIdentifier (*)(void *, CORBA_Environment *))&impl_SDOPackage_Organization_get_organization_id,
    (SDOPackage_OrganizationProperty* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Organization_get_organization_property,
    (CORBA_any* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Organization_get_organization_property_value,
    (CORBA_boolean (*)(void *, SDOPackage_OrganizationProperty*, CORBA_Environment *))&impl_SDOPackage_Organization_add_organization_property,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_any*, CORBA_Environment *))&impl_SDOPackage_Organization_set_organization_property_value,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Organization_remove_organization_property,
    (SDOPackage_SDOSystemElement (*)(void *, CORBA_Environment *))&impl_SDOPackage_Organization_get_owner,
    (CORBA_boolean (*)(void *, SDOPackage_SDOSystemElement, CORBA_Environment *))&impl_SDOPackage_Organization_set_owner,
    (SDOPackage_SDOList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_Organization_get_members,
    (CORBA_boolean (*)(void *, SDOPackage_SDOList*, CORBA_Environment *))&impl_SDOPackage_Organization_set_members,
    (CORBA_boolean (*)(void *, SDOPackage_SDOList*, CORBA_Environment *))&impl_SDOPackage_Organization_add_members,
    (CORBA_boolean (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_Organization_remove_member,
    (SDOPackage_DependencyType (*)(void *, CORBA_Environment *))&impl_SDOPackage_Organization_get_dependency,
    (CORBA_boolean (*)(void *, SDOPackage_DependencyType, CORBA_Environment *))&impl_SDOPackage_Organization_set_dependency,
};

static PortableServer_ServantBase__epv impl_RTC_ComponentAction_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_ComponentAction__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_ComponentAction__epv impl_RTC_ComponentAction_epv = {
    NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_initialize,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_finalize,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_startup,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_shutdown,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_activated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_deactivated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_aborting,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_error,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_reset,
};

static PortableServer_ServantBase__epv impl_RTC_LightweightRTObject_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_LightweightRTObject__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_LightweightRTObject__epv impl_RTC_LightweightRTObject_epv = {
    NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_initialize,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_finalize,
    (CORBA_boolean (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_is_alive,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_exit,
    (RTC_ExecutionContextHandle_t (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_attach_context,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_LightweightRTObject_detach_context,
    (RTC_ExecutionContext (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_context,
    (RTC_ExecutionContextList* (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_owned_contexts,
    (RTC_ExecutionContextList* (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_participating_contexts,
    (RTC_ExecutionContextHandle_t (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_context_handle,
};

static POA_RTC_ComponentAction__epv impl_RTC_LightweightRTObject_RTC_ComponentAction_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_initialize,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_finalize,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_startup,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_shutdown,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_activated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_deactivated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_aborting,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_error,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_reset,
};

static PortableServer_ServantBase__epv impl_RTC_ExecutionContext_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_ExecutionContext__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_ExecutionContext__epv impl_RTC_ExecutionContext_epv = {
    NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_stop,
    (CORBA_double (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_rate,
    (RTC_ReturnCode_t (*)(void *, CORBA_double, CORBA_Environment *))&impl_RTC_ExecutionContext_set_rate,
    (RTC_ExecutionKind (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_kind,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_add_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_remove_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_reset_component,
    (CORBA_boolean (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_is_running,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_start,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_activate_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_deactivate_component,
    (RTC_LifeCycleState (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_get_component_state,
};

static PortableServer_ServantBase__epv impl_RTC_PortService_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_PortService__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_PortService__epv impl_RTC_PortService_epv = {
    NULL, /* _private */
    (RTC_PortProfile* (*)(void *, CORBA_Environment *))&impl_RTC_PortService_get_port_profile,
    (RTC_ConnectorProfileList* (*)(void *, CORBA_Environment *))&impl_RTC_PortService_get_connector_profiles,
    (RTC_ConnectorProfile* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTC_PortService_get_connector_profile,
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTC_PortService_disconnect,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_PortService_disconnect_all,
    (RTC_ReturnCode_t (*)(void *, RTC_ConnectorProfile*, CORBA_Environment *))&impl_RTC_PortService_connect,
    (RTC_ReturnCode_t (*)(void *, RTC_ConnectorProfile*, CORBA_Environment *))&impl_RTC_PortService_notify_connect,
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTC_PortService_notify_disconnect,
};

static POA_SDOPackage_SDOService__epv impl_RTC_PortService_SDOPackage_SDOService_epv = 
{
     NULL, /* _private */
};

static PortableServer_ServantBase__epv impl_RTC_ExecutionContextService_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_ExecutionContextService__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_ExecutionContextService__epv impl_RTC_ExecutionContextService_epv = {
    NULL, /* _private */
    (RTC_ExecutionContextProfile* (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContextService_get_profile,
};

static POA_RTC_ExecutionContext__epv impl_RTC_ExecutionContextService_RTC_ExecutionContext_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_stop,
    (CORBA_double (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_rate,
    (RTC_ReturnCode_t (*)(void *, CORBA_double, CORBA_Environment *))&impl_RTC_ExecutionContext_set_rate,
    (RTC_ExecutionKind (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_kind,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_add_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_remove_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_reset_component,
    (CORBA_boolean (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_is_running,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_start,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_activate_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_deactivate_component,
    (RTC_LifeCycleState (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_get_component_state,
};

static POA_SDOPackage_SDOService__epv impl_RTC_ExecutionContextService_SDOPackage_SDOService_epv = 
{
     NULL, /* _private */
};

static PortableServer_ServantBase__epv impl_RTC_RTObject_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_RTObject__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_RTObject__epv impl_RTC_RTObject_epv = {
    NULL, /* _private */
    (RTC_PortServiceList* (*)(void *, CORBA_Environment *))&impl_RTC_RTObject_get_ports,
    (RTC_ComponentProfile* (*)(void *, CORBA_Environment *))&impl_RTC_RTObject_get_component_profile,
};

static POA_RTC_ComponentAction__epv impl_RTC_RTObject_RTC_ComponentAction_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_initialize,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ComponentAction_on_finalize,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_startup,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_shutdown,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_activated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_deactivated,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_aborting,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_error,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_ComponentAction_on_reset,
};

static POA_RTC_LightweightRTObject__epv impl_RTC_RTObject_RTC_LightweightRTObject_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_initialize,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_finalize,
    (CORBA_boolean (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_is_alive,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_exit,
    (RTC_ExecutionContextHandle_t (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_attach_context,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_LightweightRTObject_detach_context,
    (RTC_ExecutionContext (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_context,
    (RTC_ExecutionContextList* (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_owned_contexts,
    (RTC_ExecutionContextList* (*)(void *, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_participating_contexts,
    (RTC_ExecutionContextHandle_t (*)(void *, RTC_ExecutionContext, CORBA_Environment *))&impl_RTC_LightweightRTObject_get_context_handle,
};

static POA_SDOPackage_SDOSystemElement__epv impl_RTC_RTObject_SDOPackage_SDOSystemElement_epv = 
{
     NULL, /* _private */
    (SDOPackage_OrganizationList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDOSystemElement_get_owned_organizations,
};

static POA_SDOPackage_SDO__epv impl_RTC_RTObject_SDOPackage_SDO_epv = 
{
     NULL, /* _private */
    (SDOPackage_UniqueIdentifier (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_id,
    (CORBA_string (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_type,
    (SDOPackage_DeviceProfile* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_device_profile,
    (SDOPackage_ServiceProfileList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_service_profiles,
    (SDOPackage_ServiceProfile* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_service_profile,
    (SDOPackage_SDOService (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_sdo_service,
    (SDOPackage_Monitoring (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_monitoring,
    (SDOPackage_OrganizationList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_organizations,
    (SDOPackage_NVList* (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_status_list,
    (CORBA_any* (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_SDOPackage_SDO_get_status,
    (SDOPackage_Configuration (*)(void *, CORBA_Environment *))&impl_SDOPackage_SDO_get_configuration,
};

static PortableServer_ServantBase__epv impl_RTC_DataFlowComponentAction_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_DataFlowComponentAction__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_DataFlowComponentAction__epv impl_RTC_DataFlowComponentAction_epv = {
    NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_execute,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_state_update,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_rate_changed,
};

static PortableServer_ServantBase__epv impl_RTC_DataFlowComponent_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTC_DataFlowComponent__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTC_DataFlowComponent__epv impl_RTC_DataFlowComponent_epv = {
    NULL, /* _private */
};

static POA_RTC_DataFlowComponentAction__epv impl_RTC_DataFlowComponent_RTC_DataFlowComponentAction_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_execute,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_state_update,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_rate_changed,
};

static PortableServer_ServantBase__epv impl_OpenRTM_DataFlowComponent_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_OpenRTM_DataFlowComponent__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_OpenRTM_DataFlowComponent__epv impl_OpenRTM_DataFlowComponent_epv = {
    NULL, /* _private */
};

static POA_RTC_DataFlowComponentAction__epv impl_OpenRTM_DataFlowComponent_RTC_DataFlowComponentAction_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_execute,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_state_update,
    (RTC_ReturnCode_t (*)(void *, RTC_ExecutionContextHandle_t, CORBA_Environment *))&impl_RTC_DataFlowComponentAction_on_rate_changed,
};

static POA_RTC_DataFlowComponent__epv impl_OpenRTM_DataFlowComponent_RTC_DataFlowComponent_epv = 
{
     NULL, /* _private */
};

static PortableServer_ServantBase__epv impl_OpenRTM_ExtTrigExecutionContextService_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_OpenRTM_ExtTrigExecutionContextService__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_OpenRTM_ExtTrigExecutionContextService__epv impl_OpenRTM_ExtTrigExecutionContextService_epv = {
    NULL, /* _private */
    (void (*)(void *, CORBA_Environment *))&impl_OpenRTM_ExtTrigExecutionContextService_tick,
};

static POA_RTC_ExecutionContext__epv impl_OpenRTM_ExtTrigExecutionContextService_RTC_ExecutionContext_epv = 
{
     NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_stop,
    (CORBA_double (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_rate,
    (RTC_ReturnCode_t (*)(void *, CORBA_double, CORBA_Environment *))&impl_RTC_ExecutionContext_set_rate,
    (RTC_ExecutionKind (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_get_kind,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_add_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_remove_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_reset_component,
    (CORBA_boolean (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_is_running,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContext_start,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_activate_component,
    (RTC_ReturnCode_t (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_deactivate_component,
    (RTC_LifeCycleState (*)(void *, RTC_LightweightRTObject, CORBA_Environment *))&impl_RTC_ExecutionContext_get_component_state,
};

static POA_SDOPackage_SDOService__epv impl_OpenRTM_ExtTrigExecutionContextService_SDOPackage_SDOService_epv = 
{
     NULL, /* _private */
};

static POA_RTC_ExecutionContextService__epv impl_OpenRTM_ExtTrigExecutionContextService_RTC_ExecutionContextService_epv = 
{
     NULL, /* _private */
    (RTC_ExecutionContextProfile* (*)(void *, CORBA_Environment *))&impl_RTC_ExecutionContextService_get_profile,
};

static PortableServer_ServantBase__epv impl_RTM_Manager_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_RTM_Manager__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_RTM_Manager__epv impl_RTM_Manager_epv = {
    NULL, /* _private */
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_load_module,
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_unload_module,
    (RTM_ModuleProfileList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_loadable_modules,
    (RTM_ModuleProfileList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_loaded_modules,
    (RTM_ModuleProfileList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_factory_profiles,
    (RTC_RTObject (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_create_component,
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_delete_component,
    (RTC_RTCList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_components,
    (RTC_ComponentProfileList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_component_profiles,
    (RTM_ManagerProfile* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_profile,
    (RTM_NVList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_configuration,
    (RTC_ReturnCode_t (*)(void *, const CORBA_char *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_set_configuration,
    (CORBA_boolean (*)(void *, CORBA_Environment *))&impl_RTM_Manager_is_master,
    (RTM_ManagerList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_master_managers,
    (RTC_ReturnCode_t (*)(void *, RTM_Manager, CORBA_Environment *))&impl_RTM_Manager_add_master_manager,
    (RTC_ReturnCode_t (*)(void *, RTM_Manager, CORBA_Environment *))&impl_RTM_Manager_remove_master_manager,
    (RTM_ManagerList* (*)(void *, CORBA_Environment *))&impl_RTM_Manager_get_slave_managers,
    (RTC_ReturnCode_t (*)(void *, RTM_Manager, CORBA_Environment *))&impl_RTM_Manager_add_slave_manager,
    (RTC_ReturnCode_t (*)(void *, RTM_Manager, CORBA_Environment *))&impl_RTM_Manager_remove_slave_manager,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTM_Manager_fork,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTM_Manager_shutdown,
    (RTC_ReturnCode_t (*)(void *, CORBA_Environment *))&impl_RTM_Manager_restart,
    (CORBA_Object (*)(void *, const CORBA_char *, CORBA_Environment *))&impl_RTM_Manager_get_service,
};

static PortableServer_ServantBase__epv impl_OpenRTM_InPortCdr_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_OpenRTM_InPortCdr__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_OpenRTM_InPortCdr__epv impl_OpenRTM_InPortCdr_epv = {
    NULL, /* _private */
    (OpenRTM_PortStatus (*)(void *, OpenRTM_CdrData*, CORBA_Environment *))&impl_OpenRTM_InPortCdr_put,
};

static PortableServer_ServantBase__epv impl_OpenRTM_OutPortCdr_base_epv = {
    NULL,             /* _private data */
    (void (*)(void*, CORBA_Environment*))& impl_OpenRTM_OutPortCdr__destroy, /* finalize routine */
    NULL,             /* default_POA routine */
};

static POA_OpenRTM_OutPortCdr__epv impl_OpenRTM_OutPortCdr_epv = {
    NULL, /* _private */
    (OpenRTM_PortStatus (*)(void *, OpenRTM_CdrData**, CORBA_Environment *))&impl_OpenRTM_OutPortCdr_get,
};


/*** vepv structures ***/
static POA_SDOPackage_SDOSystemElement__vepv impl_SDOPackage_SDOSystemElement_vepv = {
    &impl_SDOPackage_SDOSystemElement_base_epv,
    &impl_SDOPackage_SDOSystemElement_epv,
};

static POA_SDOPackage_SDO__vepv impl_SDOPackage_SDO_vepv = {
    &impl_SDOPackage_SDO_base_epv,
    &impl_SDOPackage_SDO_SDOPackage_SDOSystemElement_epv,
    &impl_SDOPackage_SDO_epv,
};

static POA_SDOPackage_Configuration__vepv impl_SDOPackage_Configuration_vepv = {
    &impl_SDOPackage_Configuration_base_epv,
    &impl_SDOPackage_Configuration_epv,
};

static POA_SDOPackage_Monitoring__vepv impl_SDOPackage_Monitoring_vepv = {
    &impl_SDOPackage_Monitoring_base_epv,
    &impl_SDOPackage_Monitoring_epv,
};

static POA_SDOPackage_SDOService__vepv impl_SDOPackage_SDOService_vepv = {
    &impl_SDOPackage_SDOService_base_epv,
    &impl_SDOPackage_SDOService_epv,
};

static POA_SDOPackage_Organization__vepv impl_SDOPackage_Organization_vepv = {
    &impl_SDOPackage_Organization_base_epv,
    &impl_SDOPackage_Organization_epv,
};

static POA_RTC_ComponentAction__vepv impl_RTC_ComponentAction_vepv = {
    &impl_RTC_ComponentAction_base_epv,
    &impl_RTC_ComponentAction_epv,
};

static POA_RTC_LightweightRTObject__vepv impl_RTC_LightweightRTObject_vepv = {
    &impl_RTC_LightweightRTObject_base_epv,
    &impl_RTC_LightweightRTObject_RTC_ComponentAction_epv,
    &impl_RTC_LightweightRTObject_epv,
};

static POA_RTC_ExecutionContext__vepv impl_RTC_ExecutionContext_vepv = {
    &impl_RTC_ExecutionContext_base_epv,
    &impl_RTC_ExecutionContext_epv,
};

static POA_RTC_PortService__vepv impl_RTC_PortService_vepv = {
    &impl_RTC_PortService_base_epv,
    &impl_RTC_PortService_SDOPackage_SDOService_epv,
    &impl_RTC_PortService_epv,
};

static POA_RTC_ExecutionContextService__vepv impl_RTC_ExecutionContextService_vepv = {
    &impl_RTC_ExecutionContextService_base_epv,
    &impl_RTC_ExecutionContextService_RTC_ExecutionContext_epv,
    &impl_RTC_ExecutionContextService_SDOPackage_SDOService_epv,
    &impl_RTC_ExecutionContextService_epv,
};

static POA_RTC_RTObject__vepv impl_RTC_RTObject_vepv = {
    &impl_RTC_RTObject_base_epv,
    &impl_RTC_RTObject_RTC_ComponentAction_epv,
    &impl_RTC_RTObject_RTC_LightweightRTObject_epv,
    &impl_RTC_RTObject_SDOPackage_SDOSystemElement_epv,
    &impl_RTC_RTObject_SDOPackage_SDO_epv,
    &impl_RTC_RTObject_epv,
};

static POA_RTC_DataFlowComponentAction__vepv impl_RTC_DataFlowComponentAction_vepv = {
    &impl_RTC_DataFlowComponentAction_base_epv,
    &impl_RTC_DataFlowComponentAction_epv,
};

static POA_RTC_DataFlowComponent__vepv impl_RTC_DataFlowComponent_vepv = {
    &impl_RTC_DataFlowComponent_base_epv,
    &impl_RTC_DataFlowComponent_RTC_DataFlowComponentAction_epv,
    &impl_RTC_DataFlowComponent_epv,
};

static POA_OpenRTM_DataFlowComponent__vepv impl_OpenRTM_DataFlowComponent_vepv = {
    &impl_OpenRTM_DataFlowComponent_base_epv,
    &impl_OpenRTM_DataFlowComponent_RTC_DataFlowComponentAction_epv,
    &impl_OpenRTM_DataFlowComponent_RTC_DataFlowComponent_epv,
#if 0   /* (Added for WARNING) */
    &impl_OpenRTM_DataFlowComponent_RTC_ComponentAction__epv,
    &impl_OpenRTM_DataFlowComponent_RTC_LightweightRTObject__epv,
    &impl_OpenRTM_DataFlowComponent_SDOPackage_SDOSystemElement_epv,
    &impl_OpenRTM_DataFlowComponent_SDOPackage_SDO_epv,
    &impl_OpenRTM_DataFlowComponent_RTC_RTObject_epv,
#else
    NULL, NULL, NULL, NULL, NULL,
#endif
    &impl_OpenRTM_DataFlowComponent_epv,
};

static POA_OpenRTM_ExtTrigExecutionContextService__vepv impl_OpenRTM_ExtTrigExecutionContextService_vepv = {
    &impl_OpenRTM_ExtTrigExecutionContextService_base_epv,
    &impl_OpenRTM_ExtTrigExecutionContextService_RTC_ExecutionContext_epv,
    &impl_OpenRTM_ExtTrigExecutionContextService_SDOPackage_SDOService_epv,
    &impl_OpenRTM_ExtTrigExecutionContextService_RTC_ExecutionContextService_epv,
    &impl_OpenRTM_ExtTrigExecutionContextService_epv,
};

static POA_RTM_Manager__vepv impl_RTM_Manager_vepv = {
    &impl_RTM_Manager_base_epv,
    &impl_RTM_Manager_epv,
};

static POA_OpenRTM_InPortCdr__vepv impl_OpenRTM_InPortCdr_vepv = {
    &impl_OpenRTM_InPortCdr_base_epv,
    &impl_OpenRTM_InPortCdr_epv,
};

static POA_OpenRTM_OutPortCdr__vepv impl_OpenRTM_OutPortCdr_vepv = {
    &impl_OpenRTM_OutPortCdr_base_epv,
    &impl_OpenRTM_OutPortCdr_epv,
};


/*** Stub implementations (divide one-file(default) into each impls.) ***/
#include "impl/Impl_SDOPackage_SDOSystemElement.c"
#include "impl/Impl_SDOPackage_SDO.c"
#include "impl/Impl_SDOPackage_Configuration.c"
#include "impl/Impl_SDOPackage_Monitoring.c"
#include "impl/Impl_SDOPackage_SDOService.c"
#include "impl/Impl_SDOPackage_Organization.c"
#include "impl/Impl_RTC_ComponentAction.c"
#include "impl/Impl_RTC_LightweightRTObject.c"
#include "impl/Impl_RTC_ExecutionContext.c"
#include "impl/Impl_RTC_PortService.c"
#include "impl/Impl_RTC_ExecutionContextService.c"
#include "impl/Impl_RTC_RTObject.c"
#include "impl/Impl_RTC_DataFlowComponentAction.c"
#include "impl/Impl_RTC_DataFlowComponent.c"
#include "impl/Impl_OpenRTM_DataFlowComponent.c"
#include "impl/Impl_OpenRTM_ExtTrigExecutionContextService.c"
#include "impl/Impl_RTM_Manager.c"
#include "impl/Impl_OpenRTM_InPortCdr.c"
#include "impl/Impl_OpenRTM_OutPortCdr.c"


/*** Boohoo! ***/
